### ISSUE TITLE
scide hang

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1057]
It's not the first time it has happened but I don't have a clear reproducer. The ide hanged when entering a '('. I went into gdb and the backtrace is 

```
#0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
#1  0x00007ffcee854f1c in _L_lock_11850 () at malloc.c:5151
#2  0x00007ffcee8524c5 in __GI___libc_malloc (bytes=56) at malloc.c:2856
#3  0x00007ffcf3392660 in _dl_map_object_deps (map=map@entry=0x7ffcf35744e0, 
    preloads=preloads@entry=0x0, npreloads=npreloads@entry=0, trace_mode=trace_mode@entry=0, 
    open_mode=open_mode@entry=-2147483648) at dl-deps.c:515
#4  0x00007ffcf3398daf in dl_open_worker (a=a@entry=0x7fffdbbcc6b8) at dl-open.c:276
#5  0x00007ffcf33946e6 in _dl_catch_error (objname=objname@entry=0x7fffdbbcc6a8, 
    errstring=errstring@entry=0x7fffdbbcc6b0, mallocedp=mallocedp@entry=0x7fffdbbcc6a0, 
    operate=operate@entry=0x7ffcf3398c00 <dl_open_worker>, args=args@entry=0x7fffdbbcc6b8)
    at dl-error.c:177
#6  0x00007ffcf3398809 in _dl_open (file=0x7ffcee951b26 "libgcc_s.so.1", mode=-2147483647, 
    caller_dlopen=<optimized out>, nsid=-2, argc=1, argv=0x7fffdbbce288, env=0x7fffdbbce298)
    at dl-open.c:667
#7  0x00007ffcee906da2 in do_dlopen (ptr=ptr@entry=0x7fffdbbcc8c0) at dl-libc.c:87
#8  0x00007ffcf33946e6 in _dl_catch_error (objname=0x7fffdbbcc8a0, errstring=0x7fffdbbcc8b0, 
    mallocedp=0x7fffdbbcc890, operate=0x7ffcee906d60 <do_dlopen>, args=0x7fffdbbcc8c0)
    at dl-error.c:177
#9  0x00007ffcee906e62 in dlerror_run (args=0x7fffdbbcc8c0, operate=0x7ffcee906d60 <do_dlopen>)
    at dl-libc.c:46
#10 __GI___libc_dlopen_mode (name=name@entry=0x7ffcee951b26 "libgcc_s.so.1", 
    mode=mode@entry=-2147483647) at dl-libc.c:163
#11 0x00007ffcee8e1175 in init () at ../sysdeps/x86_64/backtrace.c:52
---Type <return> to continue, or q <return> to quit---
#12 0x00007ffcef3c2370 in pthread_once ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_once.S:103
#13 0x00007ffcee8e1294 in __GI___backtrace (array=array@entry=0x7fffdbbccb80, size=size@entry=64)
    at ../sysdeps/x86_64/backtrace.c:103
#14 0x00007ffcee843515 in __libc_message (do_abort=2, 
    fmt=fmt@entry=0x7ffcee957240 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/unix/sysv/linux/libc_fatal.c:178
#15 0x00007ffcee84ee1d in malloc_printerr (ptr=0x1f73ef0, 
    str=0x7ffcee9531e8 "corrupted double-linked list", action=<optimized out>) at malloc.c:4923
#16 malloc_consolidate (av=av@entry=0x7ffceeb90740 <main_arena>) at malloc.c:4094
#17 0x00007ffcee8500e1 in _int_malloc (av=av@entry=0x7ffceeb90740 <main_arena>, 
    bytes=bytes@entry=1025) at malloc.c:3379
#18 0x00007ffcee851ad1 in _int_realloc (av=av@entry=0x7ffceeb90740 <main_arena>, 
    oldp=oldp@entry=0x1a3e420, oldsize=528, nb=nb@entry=1040) at malloc.c:4218
#19 0x00007ffcee852ae2 in __GI___libc_realloc (oldmem=0x1a3e430, bytes=1024) at malloc.c:2984
#20 0x00007ffcf05549a4 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#21 0x00007ffcf068fd71 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#22 0x00007ffcf0691c0c in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#23 0x00007ffcf0691dd9 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#24 0x00007ffcf06927ef in QRegion::operator+=(QRegion const&) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#25 0x00007ffcf054079f in QWidgetPrivate::getOpaqueChildren() const ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
---Type <return> to continue, or q <return> to quit---
#26 0x00007ffcf0540930 in QWidgetPrivate::subtractOpaqueChildren(QRegion&, QRect const&) const ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#27 0x00007ffcf070d56c in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#28 0x00007ffcf0540fc0 in QWidgetPrivate::syncBackingStore() ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#29 0x00007ffcf0550c82 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#30 0x00007ffcf090adb3 in QMainWindow::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#31 0x00007ffcf0501dfc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#32 0x00007ffcf0508470 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#33 0x00007ffcefc898bd in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#34 0x00007ffcefc8ce1f in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#35 0x00007ffcefcb7073 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#36 0x00007ffcec6e93b6 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffcec6e9708 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffcec6e97ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffcefcb6a55 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
    () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#40 0x00007ffcf05a39d6 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
---Type <return> to continue, or q <return> to quit---
#41 0x00007ffcefc885ef in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#42 0x00007ffcefc888e5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#43 0x00007ffcefc8de5b in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#44 0x000000000042eb13 in main ()
```

**Comment by miguel-negrao** [comment]
should be fixed with qt5
