### ISSUE TITLE
supernova crashing - GVerb not supernova ready ?

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1412]
Is this a problem with GVerb or a problem with Supernova ?

```
reproducer:

g = ParGroup.new; 


SynthDef(\name,{
    var sig = SinOsc.ar([100,100.5],0,1,0);
    sig = GVerb.ar(sig);
    Out.ar(0,sig);
}).add;


(
8.do{
    Synth.head(g,\name);
}
)

gdb output:
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f0fb9728740 (LWP 745)]
memset () at ../sysdeps/x86_64/memset.S:78
78  ../sysdeps/x86_64/memset.S: Ficheiro ou directoria inexistente.

(gdb) bt
#0  memset () at ../sysdeps/x86_64/memset.S:78
#1  0x00007fb542c28942 in GVerb_Ctor () from /usr/local/lib/SuperCollider/plugins/ReverbUGens_supernova.so
#2  0x0000000000458a8e in nova::sc_synth::prepare() ()
#3  0x0000000000417757 in nova::sc_synth::perform() ()
#4  0x0000000000420bdf in nova::dsp_queue_node<nova::rt_pool_allocator<void*> >::operator()(unsigned char) ()
#5  0x0000000000417861 in nova::dsp_queue_interpreter<nova::dsp_queue_node<nova::rt_pool_allocator<void*> >, nova::rt_pool_allocator<void*> >::run_next_item(unsigned char) ()
#6  0x0000000000420de1 in void nova::dsp_queue_interpreter<nova::dsp_queue_node<nova::rt_pool_allocator<void*> >, nova::rt_pool_allocator<void*> >::run_item<false>(unsigned char) ()
#7  0x000000000042194f in nova::dsp_thread<nova::dsp_queue_node<nova::rt_pool_allocator<void*> >, nova::thread_init_functor, nova::rt_pool_allocator<void*> >::run_static(void*) ()
#8  0x00007fb55e63b182 in start_thread (arg=0x7fb55aa41740) at pthread_create.c:312
#9  0x00007fb55ce7600d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by timblechmann** [comment]
gverb tries to allocate memory, but does not handle the case that memory allocation fails.

**Comment by miguel-negrao** [comment]
Well, at least it's documented now. :)

**Comment by vivid-synth** [comment]
Is this superseded by https://github.com/supercollider/supercollider/issues/782 ?

**Comment by snappizz** [comment]
yes, it's a dupe
