### ISSUE TITLE
Cosmetic improvements to error printing

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2922]
here's the error output for `Server.default.bla`.

```
ERROR: Message 'bla' not understood.
RECEIVER:
Instance of Server {    (0x2ef84b8, gc=48, fmt=00, flg=00, set=05)
  instance variables [27]
    name : Symbol 'localhost'
    addr : instance of NetAddr (0x2ef6bd8, size=4, set=2)
    clientID : Integer 0
    userSpecifiedClientID : false
    isLocal : true
    inProcess : false
    sendQuit : nil
    remoteControlled : true
    options : instance of ServerOptions (0x2ef86e8, size=38, set=6)
    latency : Float 0.200000   9999999A 3FC99999
    dumpMode : Integer 0
    nodeAllocator : instance of NodeIDAllocator (0x2ef6418, size=6, set=3)
    controlBusAllocator : instance of ContiguousBlockAllocator (0x2ef7f38, size=5, set=3)
    audioBusAllocator : instance of ContiguousBlockAllocator (0x2ef77a8, size=5, set=3)
    bufferAllocator : instance of ContiguousBlockAllocator (0x2ef62f8, size=5, set=3)
    scopeBufferAllocator : instance of StackNumberAllocator (0x2ef6288, size=4, set=2)
    tree : nil
    syncThread : nil
    syncTasks : nil
    window : nil
    scopeWindow : nil
    emacsbuf : nil
    volume : instance of Volume (0x26331d8, size=14, set=4)
    recorder : instance of Recorder (0x262b118, size=14, set=4)
    statusWatcher : instance of ServerStatusWatcher (0x2ef99d8, size=20, set=5)
    pid : nil
    serverInterface : nil
}
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError   0x8b738c8
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x8b73818
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x8b74058
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x8b73ad8
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x8b74318
		arg this = <instance of Server>
		arg selector = 'bla'
		arg args = [*0]
	Interpreter:interpretPrintCmdLine   0x7f6ab18
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "Server.default.bla"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x8b74688
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'bla' not understood.
RECEIVER: localhost
```

there are a few inconsistencies between the receiver and call stack:

- the receiver section uses 2-space indentation and the call stack section uses tabs. i think it should be 2 or 4 spaces, but i'm okay with any consistent decision.
- the receiver section should use `=` instead of `:`.
- the call stack section doesn't need angle brackets around `<instance of Foo>`.

they're tiny issues, but i'm aiming for incremental cosmetic cleanup of the error output so it looks less like vomit.

**Comment by kisielk** [comment]
Another cosmetic thing is that the error is printed twice, and highlighted by SC-IDE only the first time (in the line that beings with `ERROR:`). However that line is often way up in the post window so it takes some scanning of the text to figure out what the actual message was. It would be great if the error was printed at the end and also highlighted as often times that can be enough to know how to resolve the problem.

**Comment by jamshark70** [comment]
> It would be great if the error was printed at the end

I'm confused. It *is* printed at the end, but not highlighted. It's fair to ask for highlighting, but there is no need to scan for the error message itself as it is already printed at the bottom.

**Comment by kisielk** [comment]
Not quite at the end, because there's also the `RECEIVER:` line, and it's partially obscured by the `^^ The preceding error dump is for...` text. If it were on its own line and highlighted it would be much easier to see at a glance.

**Comment by telephon** [comment]
Once there was the idea that we should use invisible characters from the lower ASCII set to control the highlighting. Then we could control this much better.

**Comment by kisielk** [comment]
An example of (IMO) a good stack trace is in Python:

```
Traceback (most recent call last):
  File "throwing.py", line 10, in <module>
    main()
  File "throwing.py", line 7, in main
    throws()
  File "throwing.py", line 4, in throws
    raise RuntimeError('this is the error message')
RuntimeError: this is the error message
```

It's obvious where it starts in the text because of the header, reading the stack frames is quite clear, and then the error is at the very end on its own line without any superfluous decoration.

**Comment by telephon** [comment]
We do need the trace, however (unless we save the error somewhere for introspection). You definitely want to follow the chain from beginning to end.

**Comment by telephon** [comment]
(in sclang all indentation is tabs, sorry ;-\)

**Comment by kisielk** [comment]
I don't think I mentioned eliminating the trace? It's definitely crucial. Just having the undecorated error at the end of the text, and highlighted by SC-IDE.

**Comment by kisielk** [comment]
Also is there any reason the traceback can't print the file and line number of each frame?

**Comment by jamshark70** [comment]
> Also is there any reason the traceback can't print the file and line number of each frame?

The biggest reason is that the data structure for a FunctionDef currently doesn't store line numbers. It would have to be done in a way that the interpreter backend could ignore the line number info, while ideally making it harder for data structures to get out of sync. It would have to associate line numbers with bytecode indices, because the line numbers are not necessarily sequential, e.g.

```
{
	e = Env(  // line 1
		Array.fill(5, { 1.0.rand }),
		Array.fill(4, { rrand(0.1, 0.25) })
	)
}.def.dumpByteCodes

  0   06 2E    PushSpecialClass 'Env'  // line 1
  2   06 19    PushSpecialClass 'Array'  // 2
  4   2C 05    PushInt 5
  6   04 01    PushLiteralX instance of FunctionDef - closed
  8   A3 00    SendMsg 'fill'
 10   06 19    PushSpecialClass 'Array'  // 3
 12   2C 04    PushInt 4
 14   04 02    PushLiteralX instance of FunctionDef - closed
 16   A3 00    SendMsg 'fill'
 18   C3 00    SendSpecialMsg 'new'  // 1 -- args evaluate before methods
 20   07 06    StoreInstVarX 'e'
 22   F2       BlockReturn
```

The design needs to be done carefully. It involves data structure changes in core classes, and compiler changes (not simple)... oh, and the interpreter needs to communicate the exact byte code index where the error occurred back into the Error object.

Also, you might be assuming that the interpreter has access to the entire file, but when you're executing code blocks interactively, the interpreter receives only part of the file, and it has no idea where in the code document the block appears. That could be handled by changing the signature of `interpretPrintCmdLine`.

It is, I'm afraid, not quite as simple as "just show a line number."

**Comment by kisielk** [comment]
I wasn't expecting it to be simple, just asking :) So the answer is right now there's no association between bytecode and line number.  I don't want to derail the discussion in this ticket with discussion of interpreter internals, so I'm not going to pursue any further questions there :)

**Comment by telephon** [comment]
… having paths and line numbers in the byte codes would give us great features: you could highlight the code that is currently active, you could link objects with their source code. Maybe I am too optimistic …

**Comment by kisielk** [comment]
@telephon it certainly would. Is there a ticket open for that already?

**Comment by telephon** [comment]
nobody dared so far  :)
