### ISSUE TITLE
supernova fails on init ugens

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#3566]
This is gdb output for SIGSEV in thread 45 on windows system

```
Thread 45 (Thread 4148.0x1a1c):
#0  0x0042619b in nova::sc_ugen_def::initialize (this=0x0, unit=0x4882b40)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/sc/sc_ugen_factory.hpp:84
#1  nova::sc_synth::<lambda(Unit*)>::operator() (__closure=<optimized out>, unit=0x4882b40)
    at C:\supercolliderrepos\scfork\supercollider\server\supernova\sc\sc_synth.cpp:135
#2  std::for_each<Unit**, nova::sc_synth::prepare()::<lambda(Unit*)> > (__last=0x4881558,
    __first=0x4881554, __f=...)
    at C:/i686-7.2.0-release-posix-dwarf-rt_v5-rev1/mingw32/lib/gcc/i686-w64-mingw32/7.2.0/include/c++/bits/st
l_algo.h:3884
#3  nova::sc_synth::prepare (this=0x4851778)
    at C:\supercolliderrepos\scfork\supercollider\server\supernova\sc\sc_synth.cpp:136
#4  0x0048b627 in nova::sc_synth::perform (this=0x4851778)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/sc/sc_synth.hpp:62
#5  0x0047f3d4 in nova::queue_node_data::operator() (index=0 '\000', this=0x4882bf4)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/server/dsp_thread_queue_node.hpp:50
#6  nova::dsp_queue_node<nova::rt_pool_allocator<void*> >::operator() (this=0x4882bf4,
    thread_index=0 '\000')
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/server/dsp_thread_queue_node.hpp:81
#7  0x004824d5 in nova::dsp_thread_queue_item<nova::dsp_queue_node<nova::rt_pool_allocator<void*> >, nova::rt_
pool_allocator<void*> >::run (thread_index=<optimized out>, interpreter=..., this=0x4882bf0)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/dsp_thread_queue/dsp_thread_queue.hpp:147
#8  nova::dsp_queue_interpreter<nova::dsp_queue_node<nova::rt_pool_allocator<void*> >, nova::rt_pool_allocator
<void*> >::run_next_item (this=<optimized out>, index=<optimized out>)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/dsp_thread_queue/dsp_thread_queue.hpp:624
#9  0x004826db in nova::dsp_queue_interpreter<nova::dsp_queue_node<nova::rt_pool_allocator<void*> >, nova::rt_
pool_allocator<void*> >::run_item<false> (this=0x245b58, index=0 '\000')
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/dsp_thread_queue/dsp_thread_queue.hpp:549
#10 0x004807dd in nova::dsp_queue_interpreter<nova::dsp_queue_node<nova::rt_pool_allocator<void*> >, nova::rt_
pool_allocator<void*> >::run_item_master<false> (this=<optimized out>)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/dsp_thread_queue/dsp_thread_queue.hpp:591
#11 nova::dsp_queue_interpreter<nova::dsp_queue_node<nova::rt_pool_allocator<void*> >, nova::rt_pool_allocator
<void*> >::tick_master (this=<optimized out>)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/dsp_thread_queue/dsp_thread_queue.hpp:584
#12 nova::dsp_thread_pool<nova::dsp_queue_node<nova::rt_pool_allocator<void*> >, nova::thread_init_functor, no
va::rt_pool_allocator<void*> >::run (this=<optimized out>)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/dsp_thread_queue/dsp_thread.hpp:211
#13 nova::scheduler<nova::thread_init_functor>::compute_audio (this=<optimized out>)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/server/server_scheduler.hpp:126
#14 nova::nova_server::tick (this=<optimized out>)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/server/server.hpp:245
#15 nova::run_scheduler_tick ()
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/server/server.hpp:281
#16 nova::realtime_engine_functor::run_tick ()
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/server/server.hpp:329
#17 nova::portaudio_backend<nova::realtime_engine_functor, float, false>::perform (
    statusFlags=<optimized out>, timeInfo=<optimized out>, frames=<optimized out>,
    outputBuffer=<optimized out>, inputBuffer=<optimized out>, this=<optimized out>)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/audio_backend/portaudio_backend.hpp:314
#18 nova::portaudio_backend<nova::realtime_engine_functor, float, false>::pa_process (
    input=<optimized out>, output=<optimized out>, frame_count=<optimized out>, time_info=<optimized out>,
    status_flags=<optimized out>, user_data=<optimized out>)
    at C:/supercolliderrepos/scfork/supercollider/server/supernova/audio_backend/portaudio_backend.hpp:327
#19 0x0045811f in NonAdaptingProcess (bp=bp@entry=0x265d868,
    streamCallbackResult=streamCallbackResult@entry=0xd8cfef0, hostInputChannels=0x265e4b0,
    hostOutputChannels=hostOutputChannels@entry=0x265e770, framesToProcess=<optimized out>)
    at C:\supercolliderrepos\scfork\supercollider\external_libraries\portaudio_sc_org\src\common\pa_process.c:
873
#20 0x004598f0 in PaUtil_EndBufferProcessing (bp=0x265d868,
    streamCallbackResult=streamCallbackResult@entry=0xd8cfef0)
    at C:\supercolliderrepos\scfork\supercollider\external_libraries\portaudio_sc_org\src\common\pa_process.c:
1564
#21 0x004443c0 in bufferSwitchTimeInfo (timeInfo=0x47c1d9c, index=1, directProcess=1)
    at C:\supercolliderrepos\scfork\supercollider\external_libraries\portaudio_sc_org\src\hostapi\asio\pa_asio
.cpp:3135
#22 0x73a026d3 in DllUnregisterServer ()
   from C:\Program Files (x86)\M-Audio\Fast Track Pro\MAudioFastTrackPro_Asio.dll
```

**Comment by brianlheim** [comment]
Hey @sonoro1234, what OS/version are you using?

**Comment by sonoro1234** [comment]
windows 32 bit on a 64 bit machine

**Comment by brianlheim** [comment]
Thanks, what version of SuperCollider?

**Comment by sonoro1234** [comment]
3.9

**Comment by brianlheim** [comment]
Master has tags for both 3.9.0 and 3.9.1, can you please be more specific?

**Comment by sonoro1234** [comment]
just checked with last master and it works now

**Comment by sonoro1234** [comment]
@brianlheim sorry for all the noise. Project seems quite healthy with your help.
I have been trying to understand which commit solved that issue but I coudnt.
Any idea?
