### ISSUE TITLE
scsynth crashes and exits silently if no audio socket available

### ISSUE THREAD

**Issue by 2-www** [supercollider/supercollider#6288]
## Environment

* SuperCollider version: 3.13.0
* Operating system: debian
* Other details (Qt version, audio driver, etc.): kde sdk 5.15-23.08

## Steps to reproduce
start scide in a sandbox where there's no pulse/pipewire/jack, press ctrl+b

## Expected vs. actual behavior
scsynth aborts but exits with 0. backtrace:
```
(gdb) bt
#0  0x00007ffff79bae14 in __pthread_kill_implementation () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7968dce in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff795083f in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff7cace03 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7cbfbfa in __cxxabiv1::__terminate(void (*)()) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7cbfc65 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff72a7e01 in std::__terminate () at /usr/include/c++/13.2.0/x86_64-unknown-linux-gnu/bits/c++config.h:322
#7  std::thread::~thread (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/13.2.0/bits/std_thread.h:173
#8  0x00007ffff796b4c6 in __run_exit_handlers () from /usr/lib/x86_64-linux-gnu/libc.so.6
#9  0x00007ffff796b60e in exit () from /usr/lib/x86_64-linux-gnu/libc.so.6
#10 0x00007ffff7952091 in __libc_start_call_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#11 0x00007ffff795214b in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#12 0x000055555556b085 in _start () at ../sysdeps/x86_64/start.S:115
(gdb) Quit
```

**Comment by smoge** [comment]
I believe there is no error message for this situation. 

The Non-Real-Time synthesis should work, right?

`scsynth -N cmd-file input-file output-file sample-rate header-formate sample-format`

**Comment by JordanHendersonMusic** [comment]
Thanks for this. 

libjack is a strict requirement for building supercollider, and it is also a strict requirement for running it (I believe), although this last point isn't listed on the wiki. I don't know if this should (or even could) be fixed or if the wiki should just state supercollider requires jacks to run.
