### ISSUE TITLE
(undocumented)

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#6500]
On git commit, I get this:

```
git commit -m "remove empty line"
No .pre-commit-config.yaml file was found
- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
- To permanently silence this, install pre-commit with the --allow-missing-config option
- To uninstall pre-commit run `pre-commit uninstall`
```

@capital-G – I know that pre-commit was added, but it is unclear how it is used. Should the READMEs be updated?

**Comment by capital-G** [comment]
This is interesting - are you trying to rebase https://github.com/supercollider/supercollider/pull/5923 by any chance or when exactly does this happen?

Generally speaking, it is not a problem to turn pre-commit off and on again via `pre-commit uninstall`. After merging etc. it is possible to activate it again via `pre-commit install`. At the same time I don't remember having problems switching between post-pre-commit and *pre*-pre-commit branches during the introduction).

If this is indeed the issue I'll [add a note on the wiki](https://github.com/supercollider/supercollider/wiki/Pre%E2%80%90commit), or is this something else?

**Comment by telephon** [comment]
I have done the following:
```
pip3 install pre-commit
pip install --upgrade pip
pre-commit install
>pre-commit installed at .git/hooks/pre-commit
```
Should I install pre-commit with `--allow-missing-config option`?

In any case, the information needs to be in the READMEs, since this is the first place you'd look for information.

**Comment by capital-G** [comment]
On which branch/commit does this problem appear? Recent `develop`? Can you post the output of the following commands?

```shell
which pre-commit
pre-commit --version
git rev-parse HEAD
ls -alh .pre-commit-config.yaml
```

Also you must pay attention not mix up pip/pip3 - they must not be interchangable (verify via `which pip` and `which pip3`).

I am not sure if such information needs to be in a README as `pre-commit` is a completely optional tool and only relevant for devs, not for users.
Also, we verify the integrity of the pre-commit setup during CI, so I believe it is an unforseen combination of things on your end, but it would be interesting to figure out what the problem is. If this is a more widespread problem we have to figure out what to do against this.

**Comment by capital-G** [comment]
Also - what happens if you run
* `pre-commit run`
* `pre-commit run --all-files` or
* `FULL_CHECK=1 pre-commit run --all-files`

**Comment by telephon** [comment]
`pre-commit run` returns me

```
An error has occurred: InvalidConfigError: 
=====> .pre-commit-config.yaml does not exist
Check the log at /Users/wanninger/.cache/pre-commit/pre-commit.log
```



### version information
```
pre-commit version: 2.12.1
sys.version:
    3.8.9 (v3.8.9:a743f8192b, Apr  2 2021, 08:12:53) 
    [Clang 6.0 (clang-600.0.57)]
sys.executable: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8
os.name: posix
sys.platform: darwin
```

### error information

```
An error has occurred: InvalidConfigError: 
=====> .pre-commit-config.yaml does not exist
```

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} does not exist')
cfgv.ValidationError: 
=====> .pre-commit-config.yaml does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pre_commit/main.py", line 385, in main
    return run(args.config, store, args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pre_commit/commands/run.py", line 392, in run
    config = load_config(config_file)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} does not exist')
pre_commit.clientlib.InvalidConfigError: 
=====> .pre-commit-config.yaml does not exist
```

**Comment by capital-G** [comment]
Your `pre-commit` version is somehow old, I am running `3.4.0`. But this should not be the problem after all, as the problem seems to be that `pre-commit` can nont find a `.pre-commit-config.yaml` file in the directory you run `pre-commit` in.

`pre-commit` is intended to install git hooks *per repository* according to an existing `.pre-commit-config.yaml` of the repo.
Can you verify you are running `pre-commit install` and/or `pre-commit run` on the root of a recent `develop` branch? If this is not the case, please verify that there is the file https://github.com/supercollider/supercollider/blob/develop/.pre-commit-config.yaml in your root of the repo.
If the file exists, please check the permissions of this file via `ls -alh .pre-commit-config.yaml`.

**Comment by dyfer** [comment]
FWIW I recently installed pre-commit on macOS (using pre-commit from homebrew) and it worked without issues.

**Comment by dyfer** [comment]
I'm not sure if that's related, but I had an intermittent problem with pre-commit when trying to commit in github desktop:

<img width="1384" height="850" alt="Image" src="https://github.com/user-attachments/assets/58844729-020c-4e9d-97a0-3d8cc6f1e055" />

I think it went away by itself when I restarted github desktop, OR maybe I needed to commit in the command line, and then it was okay after the app restart.

It's a bit disconcerting when committing breaks... but I guess it's okay since it went away...?

**Comment by capital-G** [comment]
IIRC this mostly happens when you are working on a branch which has not a `.pre-commit-config.yaml`, so every branch which does not include at least the commit 57f25ddef10c9f305ff468c9d205969da77af05c, i.e.  May 31, 2024
